Test compiles and tries to run; getting a Rust error
Likely need to mock out registration of logging, etc that SDK is trying
to do.

thread '<unnamed>' panicked at 'Unable to install global subscriber: SetGlobalDefaultError { _no_construct: () }', C:/bb2/src/brave/build/rustup\0.1.8\registry\src\github.com-1ecc6299db9ec823\tracing-subscriber-0.2.25\src\fmt\mod.rs:571:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\panicking.rs:101
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\result.rs:1617
   3: enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error,core::marker::Send,core::marker::Sync>,alloc::alloc::Global> >, 1, 18446744073709551615, Err>::expect
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\result.rs:1259
   4: tracing_subscriber::fmt::SubscriberBuilder<tracing_subscriber::fmt::format::DefaultFields,skus_cxx::log::CppFormatter,tracing_core::metadata::LevelFilter,std::io::stdio::Stdout (*)()>::init
             at .\brave\build\rustup\0.1.8\registry\src\github.com-1ecc6299db9ec823\tracing-subscriber-0.2.25\src\fmt\mod.rs:570
   5: skus_cxx::initialize_sdk
             at .\brave\components\skus\browser\rs\cxx\src\lib.rs:195
   6: skus_cxx::ffi::_::__initialize_sdk::__initialize_sdk
             at .\brave\components\skus\browser\rs\cxx\src\lib.rs:125
   7: skus_cxx::ffi::_::__initialize_sdk::closure$0
             at .\brave\components\skus\browser\rs\cxx\src\lib.rs:52
   8: core::panic::unwind_safe::impl$23::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\panic\unwind_safe.rs:271
   9: std::panicking::try::do_call
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\panicking.rs:403
  10: std::panicking::try
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\panicking.rs:367
  11: std::panic::catch_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\panic.rs:129
  12: cxx::unwind::catch_unwind
             at .\third_party\rust\cxx\v1\crate\src\unwind.rs:15
  13: skus_cxx::ffi::_::__initialize_sdk
             at .\brave\components\skus\browser\rs\cxx\src\lib.rs:125
  14: skus::initialize_sdk
             at .\out\Component\gen\brave\components\skus\browser\rs\cxx\src\lib.rs.cc:1236
  15: skus::SkusServiceImpl::SkusServiceImpl
             at .\brave\components\skus\browser\skus_service_impl.cc:70
  16: std::__1::make_unique
             at .\buildtools\third_party\libc++\trunk\include\__memory\unique_ptr.h:725
  17: BraveVPNServiceTest::SetUp
             at .\brave\components\brave_vpn\brave_vpn_unittest.cc:55
  18: testing::Test::Run
             at .\third_party\googletest\src\googletest\src\gtest.cc:2701
  19: testing::TestInfo::Run
             at .\third_party\googletest\src\googletest\src\gtest.cc:2885
  20: testing::TestSuite::Run
             at .\third_party\googletest\src\googletest\src\gtest.cc:3044
  21: testing::internal::UnitTestImpl::RunAllTests
             at .\third_party\googletest\src\googletest\src\gtest.cc:5914
  22: testing::UnitTest::Run
             at .\third_party\googletest\src\googletest\src\gtest.cc:5481
  23: RUN_ALL_TESTS
             at .\third_party\googletest\src\googletest\include\gtest\gtest.h:2496
  24: base::TestSuite::Run
             at .\base\test\test_suite.cc:451
  25: content::UnitTestTestSuite::Run
             at .\content\public\test\unittest_test_suite.cc:105
  26: base::OnceCallback<int ()>::Run
             at .\base\callback.h:142
  27: base::`anonymous namespace'::LaunchUnitTestsInternal
             at .\base\test\launcher\unit_test_launcher.cc:177
  28: base::LaunchUnitTests
             at .\base\test\launcher\unit_test_launcher.cc:268
  29: main
             at .\brave\test\base\run_all_unittests.cc:32
  30: invoke_main
             at D:\agent\_work\10\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  31: __scrt_common_main_seh
             at D:\agent\_work\10\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  32: BaseThreadInitThunk
  33: RtlUserThreadStart